name: KAPI
version: 1.0.0
main: com.etarruella.KAPI
api-version: 1.20
author: Erik T. Segura
description: Plugin that exposes player data in real time via WebSocket for overlays and statistics.

commands: {}

permissions: {}

