package com.etarruella.event;

public enum PlayerEventType {
    PlayerHealthChangeEvent,
    PlayerMaxHealthChangeEvent,
    PlayerPositionChangeEvent,
    PlayerSaturationChangeEvent,
    PlayerFoodLevelChangeEvent,
    PlayerPotionEffectsChangeEvent,
    PlayerArmorChangeEvent,
    PlayerExperienceChangeEvent,
    PlayerGameModeChangeEvent,
    PlayerLevelChangeEvent,
    PlayerFlyingStatusChangeEvent,
    PlayerVelocityChangeEvent,
    PlayerSneakingStatusChangeEvent,
    PlayerSprintingStatusChangeEvent,
    PlayerExhaustionChangeEvent,
    PlayerAirChangeEvent,
    PlayerFireTicksChangeEvent,
    PlayerOnGroundStatusChangeEvent,
    PlayerOpenInventoryChangeEvent,
    PlayerItemInHandChangeEvent,
    PlayerActiveSlotChangeEvent,
    PlayerXpProgressChangeEvent,
    PlayerHungerSaturationChangeEvent,
    PlayerPingChangeEvent,
    PlayerSleepingStatusChangeEvent,
    PlayerCompassTargetChangeEvent,
    PlayerJoinEvent,
    PlayerQuitEvent,
    PlayerDeathEvent,
    PlayerRespawnEvent,
}
